add api
Alex-skigo99/invoice_app pull request #1
Opened 2024-10-10 17:05 UTC by Alex-skigo99

Начал с api пока без Тестов

2024-10-10 19:07 UTC, tkachenkoas requested changes
В этом ревью большая часть комментариев сделана через голосовое распознавание поэтому текст может быть немножко кривым Имей это в виду при чтении

Общее впечатление от пулл реквеста:
- сам проверяй глазами, что ты отправляешь. Вычитывай свой код как будто это чужой код. Селф ревью - важный скилл :) 
- я возможно пропустил первую часть с каким-то фронтендом, здесь уже накатываются изменения по реакту?
- скоуп реквеста очень большой. Ты сейчас комментарии будешь править два дня :) я джунам на работе за такие пулл реквесты по жопе давал очень сильно :)

Нужно стараться разбивать полные квесты на маленькие части например:  -
- отдельно можно было бы сконфигурировать базу и написать базовый класс взаимодействия с базой а также тесты к нему 
- в следующем можно было бы сделать контроллер и подключить этот контроллер к сервисному слою
-  в третьем пуллреквесте можно было бы написать взаимодействие фронта с контроллером

Дело в том, что к каждому из этих этапов я могу оставить очень много комментариев, но сейчас они все скомканы вместе, и внесение правок может занять много времени

2024-10-10 19:07 UTC, tkachenkoas commented on build/controllers/main_controller.js
> +    readAll: async (req, res) => {
Операция ридол не должна никогда существовать в твоих контроллерах
 всегда нужно добавлять паджинацию, то есть в запросе должен приходить лимит/ размер страницы и номер страницы 

есть ещё второй вариант паджинации - это поджинация с курсором 
нужно посмотреть какую поджинацию поддерживает стандартные библиотеки ноды для монги и выбрать одну из них

Даже с учётом фильтра по статусу который тебя в контроллере количество данных в базе может быть очень большое 

За один запрос нужно возвращать не более 200 может быть 300 сущностей. Если это апи для юай, то сотки хватит

2024-10-10 19:07 UTC, tkachenkoas commented on build/controllers/main_controller.js
> +            console.error("An error occurred while reading invoices: ", error);
В первую очередь у тебя каждая операция в контроллере обёрнута в Try Catch это должно быть каким-то образом переиспользоваться по стандарту во всех операциях возможно Framework позволяет это сделать без указания этого в каждом контроллере грубо говоря ты в каком-то месте глобально с конфигурируешь что все исключения в контроллерах будут ловиться у одной общей функции и в этом случае будет возвращаться статус 500 не 404

2024-10-10 19:07 UTC, tkachenkoas commented on build/controllers/main_controller.js
> +        console.log("invoice", invoice); // debug
Для начала можно сказать что консоль Log - прокатит, но нужно будет отдельной задачей разобраться с фреймворками логирования 
В них есть различные уровни логирования инфо дебаг warning и так далее 
это нужно будет сконфигурировать
 консоль Log - это системный логирование и продакшне его не применяют потому что есть специальные логеры которые можно конфигурировать которые более мощные чем обычные консоль 
во всяком случае так в Джаве
 Я думаю что ноде есть тоже что-то похожее

2024-10-10 19:07 UTC, tkachenkoas commented on build/controllers/main_controller.js
> +            const newInvoice = await invoice_model_1.invoiceModel.create(invoice);
Почему ты не хочешь просто вернуть 200 Это самый простой вариант с ним не ошибёшься если ты возвращаешь статус 201 то ты должен возвращать ещё хедер локейшн со ссылкой на свежесозданный ресурс и при этом respons Body должен быть пустым

2024-10-10 19:07 UTC, tkachenkoas commented on build/controllers/main_controller.js
> +            console.error("An error occurred while creating an invoice: ", error);
Изучи вопрос Каким образом можно сконфигурировать общий Exception для всех контрольных в случае если вылетает то не нужно пройти прописывать в каждой операции Это должно один раз определиться для всего приложения

2024-10-10 19:07 UTC, tkachenkoas commented on build/controllers/main_controller.js
> +            res.status(206).json({ message: "Invoice updated" });
Буду частям Я чуть ли не впервые встречаю статус ответа 206 Не заморачивайся просто Используй статус 200

2024-10-10 19:07 UTC, tkachenkoas commented on build/controllers/main_controller.js
> +            res.status(204).json({ message: "Invoice deleted" });
Статус 204 обозначает No Content но при этом ты в ответе возвращаешь в message invoise deleted обычно на 204 не возвращает ничего и в целом на операцию удаления можно просто ответить статус 200 этого будет достаточно не возвращаю никакой боди

2024-10-10 19:07 UTC, tkachenkoas commented on build/models/invoice_model.js
> +            if (status)
При отправке запроса в базу твоя задача не писать 15 ифов на каждый из параметров фильтрации а один раз сделать объект query поставить в него все параметры фильтрации соответствие с со статусами и прочими параметрами и отправить его в базу

2024-10-10 19:07 UTC, tkachenkoas commented on build/models/invoice_model.js
> +            console.error("An error occurred while reading invoices: ", error);
У тебя уже есть Exception handling на уровне контроллера не нужно делать обработку исключений на каждом уровне если падает сервисный слой то пусть падает и всё это наверх летит в контроллер

2024-10-10 19:07 UTC, tkachenkoas commented on build/models/invoice_model.js
> +            await mongoDB_1.mongoClient.close();
Погугли что делает операция клиент-клоус 
Я могу ошибаться но скорее всего это делать не нужно так как приложение взаимодействует с базой через connection 

создание нового Connection - это длительная операция так как она требует проверку creedentials и много дополнительного оверхеда

 обычное приложение должно держать некий пул Connection с базой и переиспользовать эти соединения между запросами
 всяком случае так в Джаве но я думаю что в ноде должен быть такой же принцип. соединения по сети это общий паттерна, создавать их с нуля может быть очень дорого с точки зрения производительности

2024-10-10 19:07 UTC, tkachenkoas commented on build/models/invoice_model.js
> +            console.error("An error occurred while creating an invoice: ", error);
Тот же самый комментарий как и выше тебе необходимо что-то вернуть в результате выполнения операции если ты делаешь трайкетч и не возвращаешь ничего у тебя взорвётся всё так же в контроллере, тк он ждёт данные а неипустоту
если есть исключения Пусть оно летит до контроллера 
контроллер как место взаимодействия с клиентом должно отвечать за статус ответа и за обработку исключений
 Кроме этого здесь ты по сути не обрабатываешь исключение, Ты просто логируешь это бесполезно

2024-10-10 19:07 UTC, tkachenkoas commented on build/controllers/main_controller.js
>  exports.mainController = void 0;
Вообще прежде чем писать имплементацию контроллеров обычно нужно декларировать сам API то есть задокументировать пути endpoint 
для этого используется Open API спецификация а также сваггер, ты наверняка с ним знаком 
обычно контроллеры нужно разбивать по ресурсам 
 у тебя есть главный ресурс инвойс значит тебе нужно назвать инвойс-контроль и должен быть путь
/инвойсез с операциями get/post get by id patch by id

2024-10-10 19:07 UTC, tkachenkoas commented on build/controllers/main_controller.js
> +    hello: async (req, res) => {
Я к сожалению не очень хожу в таком синтаксисом ноды или экспресса и мне сложно превратить на ходу код в конкретные энт-поинты пожалуйста Поищи какую-то стандартную библиотеку которая преобразовывает твои контроллеры в проекте в Open API документацию и настрой в пакоч-джейсон стандартную операцию которая вместе с прогоном тестов также будет генерировать Open API документацию для твоих контроллеров

Это позволит мне вычитать документацию и мы сделаем её более rest-совместимой

2024-10-10 19:07 UTC, tkachenkoas commented on build/routers/main_router.js
> +exports.mainRouter.put('/invoices', main_controller_1.mainController.update);
Метод Update должен быть /invoices/:dbid Кроме этого лучше использовать патч- это более стандартный в наше время метод для апдейта ресурса, он более гибкий чем пуд

2024-10-10 19:07 UTC, tkachenkoas commented on build/types/invoice.js
> +Object.defineProperty(exports, "__esModule", { value: true });
Что происходит в этом файле? Ты описываешь модель инвойса верно? почему-то не используешь typescript?

2024-10-10 19:07 UTC, tkachenkoas commented on client/src/components/Hello.tsx
> +          if (!result) throw new Error('No data');
Есть ли какой-то реальный сценарий при котором у тебя контроллер не возвращает никакие данных? У тебя ведь как в случае успешного ответа 200 так и в случае не успешного есть какой-то  риспондс боди
 Ты сейчас пишешь код для взаимодействия со своим же сервером. ты что не доверяешь взаимодействие между своей левой и правой рукой?

2024-10-10 19:07 UTC, tkachenkoas commented on client/src/utils/http_requests.ts
> +        else throw new Error(`Response error. Status ${response.status}`);
На мой взгляд в ошибке нужно также бросать respons боди. одного статуса может быть недостаточно

2024-10-10 19:07 UTC, tkachenkoas commented on client/src/utils/http_requests.ts
> -
Если я правильно понимаю то теперь ты во всех 150.000 мест где у тебя идёт взаимодействие с сервером ты будешь выполнять одно и то же действие:

Вызов сервера, проверка статуса, try-catch, логирование 

предлагаю тебе погуглить - каким образом можно сконфигурировать твой http-клиент для того чтобы вот это правило про проверку статуса и выбрасывание исключения было описано где-то в одном месте

 если в качестве http клиента ты будешь использовать axious, то я уверен что там есть стандартные механизмы для этого для того чтобы это сделать один раз

2024-10-10 19:07 UTC, tkachenkoas commented on src/controllers/main_controller.ts
> +    readAll: async (req: Request, res: Response) => {
Я уже где-то видел мейн контроллер?

2024-10-10 19:07 UTC, tkachenkoas commented on src/models/invoice_model.ts
> +    async readAll(status: string | undefined) {
И инвойс модель я тоже где-то видел

2024-10-10 19:07 UTC, tkachenkoas commented on src/types/invoice.ts
> +type Address = {
Я правильно понимаю, что ты мне запушил и тацпскрипт, и джава скрипт?

2024-10-11 14:59 UTC, Alex-skigo99 commented on build/controllers/main_controller.js
> +    readAll: async (req, res) => {
Принял буду разбираться с пожинать нации. Плюс её надо будет скрестить ещё с фронтом.

2024-10-11 15:00 UTC, Alex-skigo99 commented on build/controllers/main_controller.js
> +            console.error("An error occurred while reading invoices: ", error);
В теме трое Кетч я плаваю. тоже надо будет понять какого правила придерживаться. буду разбираться.

2024-10-11 15:01 UTC, Alex-skigo99 commented on build/controllers/main_controller.js
> +        console.log("invoice", invoice); // debug
Да наверняка есть. Поставлю в задачи на отдельную разборку.

2024-10-11 15:17 UTC, Alex-skigo99 commented on build/controllers/main_controller.js
> +            console.error("An error occurred while creating an invoice: ", error);
Да это к вопросу try-catch

2024-10-11 15:40 UTC, tkachenkoas commented on build/controllers/main_controller.js
> +            console.error("An error occurred while reading invoices: ", error);
на фронте модно делать бесконечный скролл. я думаю библиотеки это умеют

2024-10-13 16:33 UTC, Alex-skigo99 commented on src/types/invoice.ts
> +type Address = {
Да. сейчас добавил исключение в gitignore

2024-10-13 16:44 UTC, Alex-skigo99 commented on build/routers/main_router.js
> +exports.mainRouter.put('/invoices', main_controller_1.mainController.update);
А зачем bdid если он уже есть в body

2024-10-13 16:56 UTC, merged