add filter and pagination
Alex-skigo99/invoice_app pull request #13
Opened 2024-10-22 16:42 UTC by Alex-skigo99

early.tests не смотри. это я установил плагин для Тестов и он их сам генерит. я пытался отключить, но тогда ломаются настройки, а глубоко копать неохота.
Для загрузки mockData для pagination добавил createMany.

2024-10-22 19:30 UTC, tkachenkoas requested changes
нефиг в базу лазить почти напрямую из теста :) стучись в свою же апишку

2024-10-22 19:30 UTC, tkachenkoas commented on src/__tests__/invoice.test.ts
> +            const result = await invoiceModel.createMany(paginationMockData);
А в чем проблема в цикле пройти и создать сколько нужно?

2024-10-22 19:30 UTC, tkachenkoas commented on src/__tests__/invoice.test.ts
> +            const response = await supertest(app).get("/api/invoices?page=2&limit=2");
вообще по-моему паджинация с 0 должна быть :)

2024-10-22 19:30 UTC, tkachenkoas commented on src/__tests__/invoice.test.ts
> +            const result = await invoiceModel.createMany(paginationMockData);
ну и ещё - в е2е тестах лучше напрямую в базу не лазить. у тебя есть апи создания - используй его, а потом приверяй через апи получения

2024-10-22 19:30 UTC, tkachenkoas commented on src/controllers/main_controller.ts
> +        const page = parseInt(req.query.page as string) || 1; // page is passed as query parameter for pagination
а парсИнт не взрывается когда ему нулл даешь?

2024-10-22 19:30 UTC, tkachenkoas commented on src/controllers/main_controller.ts
> +        const skip = (page - 1) * limit;
я прям ещё сильнее думаю, что паджинация с нуля должна быть. ну во всяком случае это в документаци апи должно быть быть явно указано.

а то у погромировании всё по дефолту с нуля

2024-10-22 19:30 UTC, tkachenkoas commented on src/models/invoice_model.ts
> +    async read(query: {}, options?: {}) {
я бы и query, и опшнз в один тип запихнул - и при этом бы определил конкретный интерфейс

2024-10-22 19:30 UTC, tkachenkoas commented on src/models/invoice_model.ts
> +    async create(invoice: any) {
ого, из тайпскрипта превращаемся в джаваскрипт?

2024-10-22 19:30 UTC, tkachenkoas commented on src/models/invoice_model.ts
> +    async update(dbId: string, invoice: any) {
💩

2024-10-22 19:30 UTC, tkachenkoas commented on src/models/invoice_model.ts
> +    async createMany(itemsArray: any[]) {
ну все, ради теста весь бэкенд превратили в сплошной нетипизированный ад

2024-10-22 19:30 UTC, tkachenkoas commented on src/routers/main_router.ts
> + *         description: Filter by status (draft, pending, paid)
погугли, как енум описывать. и глянь, как будет сваггер-уи выглядеть когда опишешь корректно

2024-10-22 19:30 UTC, tkachenkoas commented on src/routers/main_router.ts
> + *         example: 1
ещё можпо прописать что это нуллабл и что дефолт 0

2024-10-23 08:05 UTC, Alex-skigo99 commented on src/controllers/main_controller.ts
> +        const skip = (page - 1) * limit;
На фронте точно единицы. вопрос где делать переход либо во фронте отправлять сразу ноль, либо изменять уже в бэке. для пользователя 0-я страница это не Good :)

2024-10-23 08:07 UTC, Alex-skigo99 commented on src/controllers/main_controller.ts
> +        const page = parseInt(req.query.page as string) || 1; // page is passed as query parameter for pagination
Нет не взрывается. возвращает NaN

2024-10-23 09:47 UTC, tkachenkoas commented on src/controllers/main_controller.ts
> +        const page = parseInt(req.query.page as string) || 1; // page is passed as query parameter for pagination
Это в целом и есть "взрывается" :) ну ок

2024-10-23 09:49 UTC, tkachenkoas commented on src/controllers/main_controller.ts
> +        const skip = (page - 1) * limit;
Ну это вопрос преобразования на фронте. Ну ок, ты фреймворком или либой для паджинации не пользуешься, так что выбор за тобой

2024-10-23 11:42 UTC, merged

2024-10-23 11:48 UTC, tkachenkoas commented on src/controllers/main_controller.ts
> +        const query = (status && isValidStatus(status)) ? { status } : {}; // if status is valid, add it to query
If status is invalid, it should be a 400

2024-10-23 11:48 UTC, tkachenkoas commented on src/controllers/main_controller.ts
> +        if (Array.isArray(invoice)) {
Так никогда не делают. Сделай создание просто в цикле. Создание пачки - это может быть сложный юскейс с точки зрения валидаций и ответа

Эндпоинт должен быть сыокусированным - либо создать один, либо создать много. Не надо смешивать