add zod validation
Alex-skigo99/invoice_app pull request #15
Opened 2024-10-27 18:58 UTC by Alex-skigo99

2024-10-27 19:30 UTC, tkachenkoas requested changes

2024-10-27 19:30 UTC, tkachenkoas commented on package.json
> +    "winston-daily-rotate-file": "^5.0.0",
файл?.. гм :)

в общем, интересно посмотреть, как твоя платформа подтянет эти логи

2024-10-27 19:30 UTC, tkachenkoas commented on src/__tests__/invoice.test.ts
> +const paginationMockData: Invoice[] = statusCollection.map((status, index) => {
настоятельно не рекомендую в тестах писать "код", использовать индексы и предопределенные массивы

все значения лучше делать хардкодными, чтобы любое изменение ломало всё к чертовой матери

2024-10-27 19:30 UTC, tkachenkoas commented on src/controllers/main_controller.ts
> +        InvoiceSchema.partial().parse(invoice); // validate the input
валидацию нужно делать не в контроллере, а в логической модели/в "сервисном слое"

у тебя есть логическа операция "создать инвойс" - её могут вызывать из 300 мест:
- через ЮАЙ
- через внутренние эндпоинты
- через другие сервисные компоненты

модели пофиг, кто её вызывает - она получает данные, и перед тем, как класть в базу - делает валидацию

задача контроллера - интегрироваться с веб слоем, принять запрос, мб проверить секьюрити на операцию - и дельше пульнуть в модель (в логический/сервисный слой)

2024-10-27 19:30 UTC, tkachenkoas commented on src/types/invoice.ts
> +  street: z.string().max(100),
тесты где?

2024-10-27 19:30 UTC, tkachenkoas commented on src/types/invoice.ts
> +  street: z.string().max(100),
перенеси все эти валидаторы в отдельный класс валидатора, протестируй его вдоль и поперек

ну и потом напиши пару тестов через контроллер, чтобы посмотреть, как будет неправильный инпут отражаться в статусе ответа и в теле ответа

2024-10-27 19:30 UTC, tkachenkoas commented on src/types/invoice.ts
> +export const StatusSchema = z.enum(["paid", "pending", "draft"]);
это не очень правильно, что у тебя доменная модель зависит от библиотеки валидации

модель лучше писать на почти голом тайпскрипте - интерфейсы, числа, строки, даты, енумы - а валидаторы запихнуть в какой-то отдельный файл, чтобы вся магия валидации была только в нём. если хочешь там библиотеку использовать как имплементацию - окей. но не нужно делать, чтобы у тебя весь апи главной логический модели превращался в апи библиотеки валидации.

2024-10-28 08:51 UTC, Alex-skigo99 commented on src/types/invoice.ts
> +export const StatusSchema = z.enum(["paid", "pending", "draft"]);
да ерунда получилась, а выглядела очень удобно. верну назад

2024-10-28 09:06 UTC, Alex-skigo99 commented on src/types/invoice.ts
> +  street: z.string().max(100),
Не очень понимаю есть ли смысл тестировать библиотеку. вот если бы я сам писал валидатора то другой разговор :)

2024-10-28 12:15 UTC, tkachenkoas commented on src/types/invoice.ts
> +  street: z.string().max(100),
Ты не библиотеку тестируешь, а то, как ты её используешь и конфигурируешь
И как твоё приложение взаимодействует с исклбчениями, которые выбрасывает библиотека

2024-10-28 14:41 UTC, merged

2024-10-28 16:21 UTC, tkachenkoas commented on src/__tests__/invoice.test.ts
> +                .send({...mockData, id: '1', status: 'draft', clientName: 'Client Name1'});
Это не читаемо и не понятно, что ты шлёшь

2024-10-28 16:23 UTC, tkachenkoas commented on src/__tests__/invoice.test.ts
> +                .send({...mockData, id: '1', status: 'draft', clientName: 'Client Name1'});
Сделай захардкоженный реквест. Все равно за тебя тесты копайлот пишет, что ты экономишь строчки? В продакшенском коже нужны переменные и переиспользование данных, в тестовом коде все должно быть заинлайнено

2024-10-28 16:33 UTC, tkachenkoas requested changes

2024-10-28 16:33 UTC, tkachenkoas commented on src/__tests__/invoice.test.ts
> +                .send({...mockData, id: '4', status: 'draft', clientName: 'Client Name4'});
Я правильно понимаю, что у тебя клиент генерит айди вместо сервера? А если два одинаковых айди отправить, что будет?

2024-10-28 16:33 UTC, tkachenkoas commented on src/__tests__/invoice.test.ts
> +        it("should return 422 if pass invalid email", async () => {
Обычно 400 достаточно... 422 это уже мем про аристократического винни пуха

2024-10-28 16:33 UTC, tkachenkoas commented on src/__tests__/invoice.test.ts
> +            expect(response.body.errors[0].path[0]).toEqual('clientEmail');
У тебя тело ответа 100% предсказуемо? Если да, то сделай точный ассерт на полный ответ

2024-10-28 16:33 UTC, tkachenkoas commented on src/__tests__/invoice.test.ts
> +            expect(response.body.errors[0].path[0]).toEqual('status');
А сообщение какое? Есть что-то человекочитаемое в ответе?

2024-10-28 16:33 UTC, tkachenkoas commented on src/__tests__/validation.test.ts
> +        expect(() => InvoiceSchema.parse(invalidInvoice)).toThrow();
А что именно он выбросит? Какое сообщение, какой именно еррор? Ты уверен, что именно твоя эта валидация не прошла?

2024-10-28 16:33 UTC, tkachenkoas commented on src/__tests__/validation.test.ts
> +        expect(() => InvoiceSchema.parse(invalidInvoice)).toThrow();
Проверяй конкретную ошибку всегда

2024-10-28 16:33 UTC, tkachenkoas commented on src/__tests__/validation.test.ts
> +        expect(() => InvoiceSchema.parse(invalidInvoice)).toThrow();
Все твои тесты, как и твой код, можно поменять сотней разных способов, и все будет зелёное.

Это называется вечно зелёные тесты, которые ничего конкретного не проверяют

2024-10-28 16:33 UTC, tkachenkoas commented on src/middleware/errorMiddleware.ts
> +    logger.error(err); // Logging the validation errors
Ну вообще это не еррор, а инфо

Еррор - когда проблема у тебя, а это проблема клиента

2024-10-28 16:33 UTC, tkachenkoas commented on src/middleware/errorMiddleware.ts
> +      message: 'Data validation error',
Ради интереса можешь погуглить rfc стандарт для тела ответа с проблемами валидации :)

2024-10-28 16:33 UTC, tkachenkoas commented on src/models/invoice_model.ts
> +        InvoiceSchema.partial().parse(invoice);
Оберни эту операцию в функцию validate в классе-аалидаторе

2024-10-28 19:34 UTC, tkachenkoas commented on src/__tests__/validation.test.ts
> +    it('should invalidate an invoice with incorrect id', () => {
кстати говоря, тест ну прям такое себе отношение имеет к реальному миру

айдишники у тебя твое же приложение должно генерить, а если апдейт не существующего будет - то 404

2024-10-28 19:42 UTC, tkachenkoas reviewed
о, вот ещё нашел, до чего докопаться

2024-10-28 19:42 UTC, tkachenkoas commented on src/__tests__/validation.test.ts
> +    it('should invalidate an invoice with invalid createdAt', () => {
тоже к вопросу о реально мире: createdAt - это системное поле, которое ты сам проставляешь, апдейтить его не должно быть возможности просто на уровне запроса от клиента (т.е. ты описываешь какой-то тип `InvoiceUpdateRequest` для контроллера и игоноируешь все поля, которые не в нём)

2024-10-28 19:42 UTC, tkachenkoas commented on src/__tests__/validation.test.ts
> +            // Missing total field
в целом, паттерн "мутирование корректной модели" очень хороший

но почему в этом случае ты просто не делаешь `delete total` из валидного объекта?

2024-10-28 19:42 UTC, tkachenkoas commented on src/__tests__/validation.test.ts
> +    paymentTerms: 30,
все эти поля обязательные? если какое-то будет не предоставлено, это ошибка или нет?

на это есть тесты?

2024-10-28 19:42 UTC, tkachenkoas commented on src/__tests__/validation.test.ts
> +    it('should invalidate an invoice with incorrect items', () => {
incorrect entity = missing total?

2024-10-28 19:42 UTC, tkachenkoas commented on src/__tests__/validation.test.ts
> +        const invalidInvoice = {...validInvoice, total: -1000};
а ты связь общего тотала с тоталами из айтемов не проверяешь?
почему вообще общий тотал у тебя как поле, а не как вычисляемое проперти?

2024-10-28 19:42 UTC, tkachenkoas commented on src/__tests__/validation.test.ts
> +        const invalidInvoice = {...validInvoice, items: [{name: 'Website Design', quantity: 1, price: -1000, total: 1000}]};
между price и total есть связь какая-то? почему тотал - не формула, а поле?

2024-10-30 07:28 UTC, Alex-skigo99 commented on src/__tests__/invoice.test.ts
> +        it("should return 422 if pass invalid email", async () => {
"Проверяй конкретную ошибку всегда". Вот я и проверяю 422-я это моя конкретная ошибка валидации.

2024-10-30 07:31 UTC, Alex-skigo99 commented on src/__tests__/invoice.test.ts
> +                .send({...mockData, id: '4', status: 'draft', clientName: 'Client Name4'});
К бизнес коду я ещё не приступал. да ID должен генерироваться наверно на сервере то есть буду сверху накладывать. Да я помню что ты советовал добавлять по одному полю:)

2024-10-30 07:34 UTC, Alex-skigo99 commented on src/__tests__/invoice.test.ts
> +            expect(response.body.errors[0].path[0]).toEqual('status');
{
            "received": "draft00",
            "code": "invalid_enum_value",
            "options": [
                "paid",
                "pending",
                "draft"
            ],
            "path": [
                "status"
            ],
            "message": "Invalid enum value. Expected 'paid' | 'pending' | 'draft', received 'draft00'"
        }

2024-10-30 07:35 UTC, tkachenkoas commented on src/__tests__/invoice.test.ts
> +        it("should return 422 if pass invalid email", async () => {
Если ты пройдёшь по крупным апишкам, ты увидишь, что в основном везде просто отвечают 400 на плохой запрос. 

Гораздо важнее, чтобы внутри 400 была конкретная информация о проблеме - какой-то код, который гуглится, и в боди было читаемое человеком сообщение

2024-10-30 07:36 UTC, tkachenkoas commented on src/__tests__/invoice.test.ts
> +        it("should return 422 if pass invalid email", async () => {
Ты можешь оставить 422 если тебе прям вот так сильно хочется в эти детали хттп протокола залезть... Главное, чтобы респонс боди давал конкретику о том, в чем проблема

2024-10-30 07:37 UTC, tkachenkoas commented on src/__tests__/invoice.test.ts
> +            expect(response.body.errors[0].path[0]).toEqual('status');
Это не в комментариях гитхаба должно быть, а в тесте :))

2024-10-30 07:38 UTC, Alex-skigo99 commented on src/__tests__/validation.test.ts
> +        expect(() => InvoiceSchema.parse(invalidInvoice)).toThrow();
Да поправлю. хотя в принципе уверен потому что  валидный инвойс прошел. А если не пройдёт валидный инвойс то все тесты и так упадут.

2024-10-30 07:44 UTC, Alex-skigo99 commented on src/__tests__/validation.test.ts
> +        expect(() => InvoiceSchema.parse(invalidInvoice)).toThrow();
Понятно что за каждую букву кода отвечает программист, но вот ещё пример бесполезности AI помощника из коробки. Даже простенький тест пишет через Ж... Ну ладно польза есть как от печатной машинки ну и какие-то идеи подкидывает если синтаксис забыл. Наверно помогают кастомные настройки и передача контекста. В общем мне это видится отдельный наукой :)

2024-10-30 07:51 UTC, Alex-skigo99 commented on src/middleware/errorMiddleware.ts
> +    logger.error(err); // Logging the validation errors
Окей. мне было интересно посмотреть как logger будет разделять сообщение по разным файлам и разным форматам отображения.

2024-10-30 08:08 UTC, Alex-skigo99 commented on src/middleware/errorMiddleware.ts
> +      message: 'Data validation error',
Этот стандарт?
RFC 9457
Problem Details for HTTP APIs

Да вот такой пример приводится для валидации:

HTTP/1.1 422 Unprocessable Content
Content-Type: application/problem+json
Content-Language: en

{
 "type": "https://example.net/validation-error",
 "title": "Your request is not valid.",
 "errors": [
             {
               "detail": "must be a positive integer",
               "pointer": "#/age"
             },
             {
               "detail": "must be 'green', 'red' or 'blue'",
               "pointer": "#/profile/color"
             }
          ]
}

2024-10-30 08:15 UTC, Alex-skigo99 commented on src/__tests__/invoice.test.ts
> +                .send({...mockData, id: '1', status: 'draft', clientName: 'Client Name1'});
"в целом, паттерн "мутирование корректной модели" очень хороший"  так я его здесь и применяю.

2024-10-30 10:24 UTC, Alex-skigo99 commented on src/__tests__/validation.test.ts
> +    it('should invalidate an invoice with invalid createdAt', () => {
По условию немного не так. если счёт сохраняется как Draft то могут быть все поля пустыми. при окончательном сохранении createdAt апдейтится. есть три вычисляемых поля ID = 'AB123', paymentDue = createdAt + paymentTerms, total = Sum(items(total)). ID можно формировать на сервере, a paymentDue, total надо показать пользователю в форме при заполнении, поэтому их можно отправить в request. или лучше вообще не сохранять так как это вычисляемая информация. С другой стороны может понадобиться отсортировать счета по дате оплаты и по сумме тогда эти поля пригодятся в базе. что думаешь?

2024-10-30 10:54 UTC, tkachenkoas commented on src/__tests__/invoice.test.ts
> +                .send({...mockData, id: '4', status: 'draft', clientName: 'Client Name4'});
Я как чукча - что вижу, о том и пою :) добавлял бы по одному полю, вопросов бы было меньше :)

2024-10-30 10:57 UTC, tkachenkoas commented on src/middleware/errorMiddleware.ts
> +      message: 'Data validation error',
Да, наверное этот. Это просто к тому, что ты сейчас завязал формат ответа на какую-то там библиотеку. Это хорошо, что она даёт подробную инфу, но если у тебя будет какое-то другое исключение, то формат ответа у тебя будет другой

Кстати, структуру респонс боди для не-200 ответа тоже полезно описать в документации апи :)

Хз как в вашей ноде это сделать, чтобы на все эндпоинты сразу добавить структуру для 400 :)

2024-10-30 11:03 UTC, Alex-skigo99 commented on src/__tests__/validation.test.ts
> +            // Missing total field
Можно и так просто надо будет отдельно типизировать корректную модель чтобы какие-то поля сделать не обязательными. Я вначале про это думал потом оставил то что Copilot нагенерил :)

2024-10-30 11:05 UTC, Alex-skigo99 commented on src/__tests__/validation.test.ts
> +    paymentTerms: 30,
Тут какая штука выходит если данные прилетают со статусом драфт то поля могут быть любыми если со статусом Pending то поля все обязательно. Может быть всё-таки сделать отдельно патч и пут.

2024-10-30 11:17 UTC, tkachenkoas commented on src/__tests__/validation.test.ts
> +    paymentTerms: 30,
Типичный механизм патча - это когда ты идёшь в базу, достаёшь существующее, потом применяешь патч из запроса, а потом сохраняешь

 ключевая идею: объект запроса, объект бизнес модели и объект который ты хранишь в базе - это три больших разницы, у каждого своя цель. У них в теории и поля по разному могут называться, что аж придётся конвертировать между ними. Просто так брать запрос из контроллера и слать его на валидацию и в базу нельзя

2024-10-30 11:28 UTC, tkachenkoas commented on src/__tests__/validation.test.ts
> +    it('should invalidate an invoice with invalid createdAt', () => {
Ну тогда надо ифы всякие писать, а не просто модельку настроить из библиотеки за три секунды

2024-10-30 11:31 UTC, tkachenkoas commented on src/__tests__/validation.test.ts
> +    it('should invalidate an invoice with invalid createdAt', () => {
Фронтенд вроде сам умеет вычислять тотал, слать смысла нет

Насчёт базы - зависит. В примитивном решении можно наверняка в базе сортировать по вычисляемому полю. В долгосроке наверное захочется хранить поле хардкодно, чтобы индекс работал. Смотри мой коммент выше о том, что логическая модель, запрос-ответ клиентам и данные в базе - это три разных мира